version: '3'

tasks:
  run:
    desc: "Run service"
    cmd: go run cmd/chat/main.go
    env:
      CONFIG_PATH: "config/local.yaml"

  build:
    desc: "Build service"
    cmd: go build -o build/chat cmd/chat/main.go

  swag-gen:
    desc: "Generate Swagger docs"
    cmd: swag init -g cmd/chat/main.go --output docs

  mock-gen:
    desc: "Generate mock interfaces"
    cmd: mockery

  test-unit-handler:
    desc: "Run unit handler tests"
    cmd: go test -v ./internal/http/handler/...

  test-unit-service:
    desc: "Run unit service tests"
    cmd: go test -v ./internal/service/...

  postgres-up:
    desc: "Start PostgreSQL container"
    cmd: docker compose up postgres -d

  postgres-down:
    desc: "Stop PostgreSQL container"
    cmd: docker compose down postgres

  golangci-lint:
    desc: "Lint repository code"
    cmds:
      - task: golangci-lint-{{.mode}}
    requires:
      vars: [mode]

  golangci-lint-dry:
    internal: true
    cmd: golangci-lint run

  golangci-lint-fix:
    internal: true
    cmd: golangci-lint run --fix

  goose:
    dotenv: [".env"]
    desc: Run goose migrations
    cmd: |
          goose -dir ./migrations postgres \
            "host=${POSTGRES_HOST} \
            port=${POSTGRES_PORT} \
            user=${POSTGRES_USER} \
            password=${POSTGRES_PASSWORD} \
            dbname=${POSTGRES_DB} \
            sslmode=disable" \
            {{default "status" .mode}}