// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "chat-service/internal/repository/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteChat provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteChat(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type MockRepository_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) DeleteChat(ctx interface{}, id interface{}) *MockRepository_DeleteChat_Call {
	return &MockRepository_DeleteChat_Call{Call: _e.mock.On("DeleteChat", ctx, id)}
}

func (_c *MockRepository_DeleteChat_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteChat_Call) Return(_a0 error) *MockRepository_DeleteChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteChat_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// InsertChat provides a mock function with given fields: ctx, chat
func (_m *MockRepository) InsertChat(ctx context.Context, chat *models.Chat) error {
	ret := _m.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for InsertChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Chat) error); ok {
		r0 = rf(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChat'
type MockRepository_InsertChat_Call struct {
	*mock.Call
}

// InsertChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *models.Chat
func (_e *MockRepository_Expecter) InsertChat(ctx interface{}, chat interface{}) *MockRepository_InsertChat_Call {
	return &MockRepository_InsertChat_Call{Call: _e.mock.On("InsertChat", ctx, chat)}
}

func (_c *MockRepository_InsertChat_Call) Run(run func(ctx context.Context, chat *models.Chat)) *MockRepository_InsertChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Chat))
	})
	return _c
}

func (_c *MockRepository_InsertChat_Call) Return(_a0 error) *MockRepository_InsertChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertChat_Call) RunAndReturn(run func(context.Context, *models.Chat) error) *MockRepository_InsertChat_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMessage provides a mock function with given fields: ctx, message
func (_m *MockRepository) InsertMessage(ctx context.Context, message *models.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for InsertMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMessage'
type MockRepository_InsertMessage_Call struct {
	*mock.Call
}

// InsertMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *models.Message
func (_e *MockRepository_Expecter) InsertMessage(ctx interface{}, message interface{}) *MockRepository_InsertMessage_Call {
	return &MockRepository_InsertMessage_Call{Call: _e.mock.On("InsertMessage", ctx, message)}
}

func (_c *MockRepository_InsertMessage_Call) Run(run func(ctx context.Context, message *models.Message)) *MockRepository_InsertMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Message))
	})
	return _c
}

func (_c *MockRepository_InsertMessage_Call) Return(_a0 error) *MockRepository_InsertMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertMessage_Call) RunAndReturn(run func(context.Context, *models.Message) error) *MockRepository_InsertMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SelectChat provides a mock function with given fields: ctx, id
func (_m *MockRepository) SelectChat(ctx context.Context, id uint) (*models.Chat, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SelectChat")
	}

	var r0 *models.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Chat, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Chat); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SelectChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectChat'
type MockRepository_SelectChat_Call struct {
	*mock.Call
}

// SelectChat is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) SelectChat(ctx interface{}, id interface{}) *MockRepository_SelectChat_Call {
	return &MockRepository_SelectChat_Call{Call: _e.mock.On("SelectChat", ctx, id)}
}

func (_c *MockRepository_SelectChat_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_SelectChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_SelectChat_Call) Return(_a0 *models.Chat, _a1 error) *MockRepository_SelectChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SelectChat_Call) RunAndReturn(run func(context.Context, uint) (*models.Chat, error)) *MockRepository_SelectChat_Call {
	_c.Call.Return(run)
	return _c
}

// SelectMessages provides a mock function with given fields: ctx, chatID, limit
func (_m *MockRepository) SelectMessages(ctx context.Context, chatID uint, limit int) ([]*models.Message, error) {
	ret := _m.Called(ctx, chatID, limit)

	if len(ret) == 0 {
		panic("no return value specified for SelectMessages")
	}

	var r0 []*models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) ([]*models.Message, error)); ok {
		return rf(ctx, chatID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) []*models.Message); ok {
		r0 = rf(ctx, chatID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int) error); ok {
		r1 = rf(ctx, chatID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SelectMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectMessages'
type MockRepository_SelectMessages_Call struct {
	*mock.Call
}

// SelectMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - limit int
func (_e *MockRepository_Expecter) SelectMessages(ctx interface{}, chatID interface{}, limit interface{}) *MockRepository_SelectMessages_Call {
	return &MockRepository_SelectMessages_Call{Call: _e.mock.On("SelectMessages", ctx, chatID, limit)}
}

func (_c *MockRepository_SelectMessages_Call) Run(run func(ctx context.Context, chatID uint, limit int)) *MockRepository_SelectMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_SelectMessages_Call) Return(_a0 []*models.Message, _a1 error) *MockRepository_SelectMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SelectMessages_Call) RunAndReturn(run func(context.Context, uint, int) ([]*models.Message, error)) *MockRepository_SelectMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
