// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "chat-service/internal/repository/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function with given fields: ctx, chat
func (_m *MockService) CreateChat(ctx context.Context, chat *models.Chat) error {
	ret := _m.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Chat) error); ok {
		r0 = rf(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type MockService_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *models.Chat
func (_e *MockService_Expecter) CreateChat(ctx interface{}, chat interface{}) *MockService_CreateChat_Call {
	return &MockService_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, chat)}
}

func (_c *MockService_CreateChat_Call) Run(run func(ctx context.Context, chat *models.Chat)) *MockService_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Chat))
	})
	return _c
}

func (_c *MockService_CreateChat_Call) Return(_a0 error) *MockService_CreateChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateChat_Call) RunAndReturn(run func(context.Context, *models.Chat) error) *MockService_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function with given fields: ctx, msg
func (_m *MockService) CreateMessage(ctx context.Context, msg *models.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockService_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *models.Message
func (_e *MockService_Expecter) CreateMessage(ctx interface{}, msg interface{}) *MockService_CreateMessage_Call {
	return &MockService_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, msg)}
}

func (_c *MockService_CreateMessage_Call) Run(run func(ctx context.Context, msg *models.Message)) *MockService_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Message))
	})
	return _c
}

func (_c *MockService_CreateMessage_Call) Return(_a0 error) *MockService_CreateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateMessage_Call) RunAndReturn(run func(context.Context, *models.Message) error) *MockService_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChatByID provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteChatByID(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChatByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChatByID'
type MockService_DeleteChatByID_Call struct {
	*mock.Call
}

// DeleteChatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) DeleteChatByID(ctx interface{}, id interface{}) *MockService_DeleteChatByID_Call {
	return &MockService_DeleteChatByID_Call{Call: _e.mock.On("DeleteChatByID", ctx, id)}
}

func (_c *MockService_DeleteChatByID_Call) Run(run func(ctx context.Context, id uint)) *MockService_DeleteChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockService_DeleteChatByID_Call) Return(_a0 error) *MockService_DeleteChatByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteChatByID_Call) RunAndReturn(run func(context.Context, uint) error) *MockService_DeleteChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatByID provides a mock function with given fields: ctx, id, limit
func (_m *MockService) GetChatByID(ctx context.Context, id uint, limit int) (*models.Chat, error) {
	ret := _m.Called(ctx, id, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByID")
	}

	var r0 *models.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) (*models.Chat, error)); ok {
		return rf(ctx, id, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) *models.Chat); ok {
		r0 = rf(ctx, id, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int) error); ok {
		r1 = rf(ctx, id, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByID'
type MockService_GetChatByID_Call struct {
	*mock.Call
}

// GetChatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - limit int
func (_e *MockService_Expecter) GetChatByID(ctx interface{}, id interface{}, limit interface{}) *MockService_GetChatByID_Call {
	return &MockService_GetChatByID_Call{Call: _e.mock.On("GetChatByID", ctx, id, limit)}
}

func (_c *MockService_GetChatByID_Call) Run(run func(ctx context.Context, id uint, limit int)) *MockService_GetChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(int))
	})
	return _c
}

func (_c *MockService_GetChatByID_Call) Return(_a0 *models.Chat, _a1 error) *MockService_GetChatByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetChatByID_Call) RunAndReturn(run func(context.Context, uint, int) (*models.Chat, error)) *MockService_GetChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
