// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package helpers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE34310f8DecodeChatServiceInternalHttpUtilsHelpers(in *jlexer.Lexer, out *apiError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE34310f8EncodeChatServiceInternalHttpUtilsHelpers(out *jwriter.Writer, in apiError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE34310f8EncodeChatServiceInternalHttpUtilsHelpers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE34310f8EncodeChatServiceInternalHttpUtilsHelpers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE34310f8DecodeChatServiceInternalHttpUtilsHelpers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE34310f8DecodeChatServiceInternalHttpUtilsHelpers(l, v)
}
